// src/app/(overlay)/overlay/page.tsx
"use client";

import { CrosshairItem, defaultCrosshairs } from "@/lib/crosshair";
import { useSettings } from "@/components/settings-provider";
import { Settings, type CrosshairSettings, type OverlaySettings } from "@/lib/types";
import { listen } from "@tauri-apps/api/event";
import { availableMonitors, getCurrentWindow, Window } from "@tauri-apps/api/window";
import { useCallback, useEffect, useRef, useState } from "react";
import { objEquals } from "@/lib/utils";

type Notification = {
    icon?: string;
    title: string;
    message: string;
}

export default function Overlay() {
    const [w, setW] = useState<Window | null>(null);
    let { loading, settings } = useSettings();

    const [notifications, setNotifications] = useState<Notification[]>([]);
    const [crosshairSettings, setCrosshairSettings] = useState<CrosshairSettings>();
    const [crosshairStyles, setCrosshairStyles] = useState<React.CSSProperties>();
    const [crosshair, setCrosshair] = useState<CrosshairItem>();
    const [showCrosshair, setShowCrosshair] = useState<boolean>(false);

    const overlaySettingsRef = useRef<OverlaySettings | null>(null);

    const notificationRef = useRef<HTMLDivElement>(null);

    const updateCrosshair = (crosshair: CrosshairSettings) => {
        setCrosshairSettings(crosshair);
        setCrosshairStyles({
            "fill": crosshair.color,
            "stroke": crosshair.color,
            "color": crosshair.color,
            "width": crosshair.size + "px",
            "height": crosshair.size + "px",
            "marginTop": crosshair.offset.y + "px",
            "marginLeft": crosshair.offset.x + "px",
        });
        setCrosshair(defaultCrosshairs.find((c) => c.id === crosshair.selected));
    }

    const load = useCallback(async (overlay?: OverlaySettings, w?: Window | null) => {
        if (!overlay || !w) return;

        if (!overlay.enabled) {
            await w.hide();
            return;
        }

        const avail = await availableMonitors();
        const display = avail.find((m) => m.name === overlay.display);
        if (!display) return;

        const maximised = await w.isMaximized();
        if (maximised) await w.unmaximize();
        await w.setSize(display.size);
        await w.setPosition(display.position);
        await w.setSimpleFullscreen(false);
        await w.setDecorations(false);
        await w.setTitleBarStyle("transparent");
        await w.setIgnoreCursorEvents(true);
        await w.maximize();
        await w.show();
    }, []);

    const debounceRef = useRef<NodeJS.Timeout | undefined>(undefined);

    useEffect(() => {
        if (!overlaySettingsRef.current || !w) return;

        clearTimeout(debounceRef.current);
        debounceRef.current = setTimeout(() => {
            load(overlaySettingsRef.current!, w);
        }, 200); // 200ms debounce
    }, [overlaySettingsRef.current, w, load]);


    useEffect(() => {
        if (loading || !settings) return;
        settings.overlay && (overlaySettingsRef.current = settings.overlay);
        settings.crosshair && updateCrosshair(settings.crosshair);
    }, [loading, settings]);

    useEffect(() => {
        const w = getCurrentWindow();
        w && setW(w);

        const unlisten = Promise.all([
            listen<boolean>("toggle-overlay", async (event) => {
                if (!w) return;
                event.payload ? await w.show() : await w.hide();
            }),
            listen<CrosshairSettings>("update-crosshair", async (event) => {
                if (!w) return;
                updateCrosshair(event.payload);
            }),
            listen<boolean>("show-crosshair", async (event) => {
                setShowCrosshair(event.payload);
            }),
            listen<Settings>("settings-updated", async (event) => {
                const payload = event.payload;
                settings = payload;

                const eq = objEquals(overlaySettingsRef.current!, payload.overlay);
                if (!eq)
                    overlaySettingsRef.current = payload.overlay;

                updateCrosshair(payload.crosshair);
            })
        ])

        return () => {
            unlisten.then((fns) => fns.forEach((fn) => fn()));
        };
    }, []);

    if (loading) return (<></>)

    return (
        <div className="flex w-full h-screen relative">
            <div id="notifications" ref={notificationRef} className="absolute top-4 left-4">
                <div className="relative">
                    {notifications.map((n, i) => (
                        <div key={i} onClick={() => console.log("abc")} className={`absolute bg-sidebar p-2 rounded shadow flex gap-4 w-[300px] pointer-events-auto`}>
                            <img className="rounded shadow" src="https://placehold.co/64" alt="Notification" />
                            <div className="space-y-1">
                                <h2 className="font-bold text-muted-foreground">{n.title}</h2>
                                <p className="text-muted-foreground text-sm">{n.message}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
            {(crosshair && crosshairSettings?.enabled && showCrosshair) && (
                <div
                    className="flex justify-center items-center pointer-events-none w-full h-full"
                >
                    <crosshair.content style={crosshairStyles} />
                </div>
            )}
        </div>
    )
}

// src/pages/overlay.vue
<script setup lang="ts">
import { emitTo, listen } from '@tauri-apps/api/event';
import { availableMonitors, primaryMonitor, getCurrentWindow } from '@tauri-apps/api/window';
import type { CrosshairSettings } from '~/utils/settings';

type Notification = {
    title: string;
    body: string;
    icon?: string;
}

let timeout: NodeJS.Timeout | null = null;
const notif = ref<Notification | null>(null);

const display = ref()

const showCrosshair = ref(false);
const crosshairEnabled = ref(false);
const crosshairId = ref<string | null>(null);
const crosshairIcon = ref<any>(null);
const crosshairColor = ref('#000');
const crosshairSize = ref(20);
const offset = reactive({ x: 0, y: 0 });

onMounted(async () => {
    const crosshairSettings = getSetting<CrosshairSettings>('crosshair');
    if (!crosshairSettings) return;

    crosshairEnabled.value = crosshairSettings.enabled;
    crosshairId.value = crosshairSettings.selected;
    crosshairColor.value = crosshairSettings.color;
    crosshairSize.value = crosshairSettings.size;
    display.value = crosshairSettings.display;
    offset.x = crosshairSettings.offset.x;
    offset.y = crosshairSettings.offset.y;
    updateCrosshair();
});

const current = getCurrentWindow();
const overlayVisible = ref(false);
const close = async () => {
    overlayVisible.value = false;
    current.setIgnoreCursorEvents(true);
}

const showUnlisten = await listen<{
        visible: boolean;
    }>('toggle-overlay', (event) => {
        overlayVisible.value = !overlayVisible.value;

        if (overlayVisible.value) {
            current.setIgnoreCursorEvents(false);
            current.setFullscreen(true);
            current.setFocus();
        } else {
            current.setIgnoreCursorEvents(true);
            current.setFullscreen(false);
            current.maximize();
        }
});

listen<{
        enabled: boolean;
    }>('show-crosshair', (event) => {
    showCrosshair.value = event.payload.enabled;
});

const crosshairListener = await listen<boolean>('toggle-crosshair', (event) => {
        crosshairEnabled.value = event.payload;
});

await listen<{
    id: string;
    color: string;
    size: number;
    display: string;
    offset: { x: number; y: number };
}>("set-crosshair", (event) => {
    crosshairId.value = event.payload.id;
    crosshairColor.value = event.payload.color;
    crosshairSize.value = event.payload.size;
    display.value = event.payload.display;
    offset.x = event.payload.offset.x;
    offset.y = event.payload.offset.y;
    updateCrosshair();
});

const crosshairStyles = computed(() => ({
    '--crosshair-fill': crosshairColor.value,
    '--crosshair-size': `${crosshairSize.value}px`,
    '--crosshair-offset-x': `${offset.x}px`,
    '--crosshair-offset-y': `${offset.y}px`,
}));

function updateCrosshair() {
    const crosshairs = defaultCrosshairs;
    const selected = crosshairs.find((c) => c.id === crosshairId.value);
    if (selected) crosshairIcon.value = selected.content;
    else crosshairIcon.value = null;

    const crosshairSettings = getSetting<CrosshairSettings>('crosshair') || DEFAULT_CROSSHAIR;
    crosshairSettings.color = crosshairColor.value;
    crosshairSettings.size = crosshairSize.value;
    crosshairSettings.selected = crosshairId.value;
    crosshairSettings.display = display.value;
    crosshairSettings.offset = offset;

    availableMonitors().then(async (monitors) => {
        const selectedMonitor = monitors.find((m) => m.name === display.value) || await primaryMonitor();
        if (!selectedMonitor) return;

        const position = selectedMonitor.position;
        await current.setPosition(position);
        current.setShadow(false);
        const isMaximized = await current.isMaximized();
        if (!isMaximized) current.maximize();
    });

    setSetting('crosshair', crosshairSettings);
}

const audio = ref<HTMLAudioElement | null>(null)
function showNotif(payload: Notification) {
    notif.value = payload;
    if (audio.value) audio.value.play();

    timeout = setTimeout(() => {
        notif.value = null;
        if (timeout) clearTimeout(timeout);
    }, 5000);
}

const notificationListener = await listen<Notification>('notification', (event) => {
    if (notif.value) {
        notif.value = null;
        if (timeout) clearTimeout(timeout);
        setTimeout(showNotif, 500);
        return;
    }

    showNotif(event.payload);
});

onMounted(() => {
    const cards = document.querySelectorAll('.card');

    cards.forEach((card: any) => {
        const dragArea = card.querySelector('.drag-area');
        const content = card.querySelector('.content');

        dragArea.addEventListener('mousedown', (e: any) => {
            let offsetX = e.clientX - card.getBoundingClientRect().left;
            let offsetY = e.clientY - card.getBoundingClientRect().top;
            let isDragging = true;

            cards.forEach((c: any) => c.style.zIndex = 0);
            card.style.zIndex = 1;

            document.addEventListener('mousemove', (e: any) => {
                if (!isDragging) return;
                card.style.left = e.clientX - offsetX + 'px';
                card.style.top = e.clientY - offsetY + 'px';
            });

            document.addEventListener('mouseup', () => {
                document.removeEventListener('mousemove', () => {});
                document.removeEventListener('mouseup', () => {});

                isDragging = false;
            });
        });
    });
})
</script>

<template>
    <div id="overlay">
        <audio ref="audio" src="assets/audio/notification.mp3"></audio>
        <div class="overlay" :class="{ 'hidden': !overlayVisible }">
            <div class="close" @click="close">
                <Icon name="codicon:chrome-close" />
            </div>
            <div class="cards">
                <div class="card">
                    <div class="drag-area">
                        <span class="line"></span>
                    </div>
                    
                    <div class="content">
                        <h2>Card 1</h2>
                        <p>Content 1</p>
                    </div>
                </div>
                <div class="card">
                    <div class="drag-area">
                        <span class="line"></span>
                    </div>
                    
                    <div class="content">
                        <h2>Card 2</h2>
                        <p>Content 2</p>
                    </div>
                </div>
                <div class="card">
                    <div class="drag-area">
                        <span class="line"></span>
                    </div>
                    
                    <div class="content">
                        <h2>Card 3</h2>
                        <p>Content 3</p>
                    </div>
                </div>
            </div>
        </div>
        <div id="crosshair" v-if="!overlayVisible && crosshairEnabled && crosshairIcon && showCrosshair">
            <component :is="crosshairIcon" class="crosshair-svg" :style="crosshairStyles" />
        </div>
        <!--<div id="notifications" class="absolute left-2 top-2 min-w-[300px]">
            <div class="flex notif bg-zinc-900 p-3" :class="{ 'show-notif': !!notif, 'hide-notif': !notif }">
                <img v-if="notif && notif.icon" class="h-[50px] w-[50px]" :src="notif.icon" alt="Notification" />
                <div class="ml-4" v-if="notif">
                    <h3 class="font-bold text-ellipsis ws-nowrap overflow-hidden">{{ notif.title }}</h3>
                    <p class="opacity-85 mt-1 text-sm text-ellipsis ws-nowrap overflow-hidden">{{ notif.body }}</p>
                </div>
            </div>
        </div>-->
    </div>
</template>

<style lang="scss">
#notifications {
    transition: all 0.3s ease;
    pointer-events: none;

    .notif {
        border-radius: 12px;
        transition: all 0.5s ease;

        &.show-notif {
            transform: translateY(0);
        }

        &.hide-notif {
            transform: translateY(-150%);
        }
    }

    img {
        border-radius: 8px;
    }
}

#crosshair {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100svh;
    width: 100svw;
}

.crosshair-svg {
    margin-top: var(--crosshair-offset-y);
    margin-left: var(--crosshair-offset-x);
    width: var(--crosshair-size);
    height: var(--crosshair-size);
}

.crosshair-svg, .crosshair-svg * {
    fill: var(--crosshair-fill);
    stroke: var(--crosshair-fill);
}

.overlay {
    background-color: rgba(0, 0, 0, 0.4);
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    width: 100%;
    height: 100%;
    z-index: 1000;
    color: white;
    font-weight: 500;

    .close {
        position: absolute;
        top: 10px;
        right: 10px;
        cursor: pointer;
        width: 40px;
        height: 40px;
        border-radius: 5px;
        background-color: #444;
        font-size: 20px;
        color: #ccc;
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1001;

        &:hover {
            background-color: #333;
            color: white;
        }
    }

    .cards {
        .card {
            position: absolute;
            top: 0;
            left: 0;

            width: 300px;
            height: 200px;
            background-color: var(--color-background);
            color: var(--color-text);
            border-radius: 5px;
            box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.5); 

            .drag-area {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 2em;
                cursor: move;
                background-color: var(--color-sidebar);
                border-radius: 5px 5px 0 0;
                box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);

                .line {
                    width: 50%;
                    height: 2px;
                    background-color: var(--color-text);
                }
            }

            .content {
                padding: .5em 1em;

                h2 {
                    font-size: 1.5rem;
                    font-weight: 700;
                }

                p {
                    font-size: 1rem;
                    font-weight: 500;
                }
            }
        }
    }
}
</style>
