// src/components/sidebar.tsx
"use client";

import { cn } from '@/lib/utils';
import styles from './sidebar.module.scss';
import { User, getUser, signIn } from 'tauri-plugin-authium-api';
import { useEffect, useState } from 'react';
import Image, { StaticImageData } from 'next/image';
import Link from 'next/link';
import { Clock, Crosshair, GamepadIcon, Heart, House, LogIn, MessageCircle, Settings, Users, Video } from 'lucide-react';
import { usePathname } from 'next/navigation';

export default function Sidebar() {
    const [loading, setLoading] = useState(true);
    const [user, setUser] = useState<User | null>(null);
    const [avatar, setAvatar] = useState<string | StaticImageData>();
    const [activePage, setActivePage] = useState<string | null>(null);

    const page = usePathname();

    let defaultAvatar: StaticImageData;
    useEffect(() => {
        const load = async () => {
            defaultAvatar = (await import('@/assets/img/default-photo.png')).default;

            const user = await getUser();
            user && setUser(user);

            setAvatar(user?.avatar || defaultAvatar);
            setLoading(false);
        }
        load();
    }, []);

    useEffect(() => {
        setActivePage(page);
    }, [page]);

    return (
        <aside className={cn("w-64 h-full bg-sidebar text-white flex flex-col items-center py-5 z-50", styles.sidebar)}>
            <div className="w-full flex flex-col items-center mb-5">
                <div className="flex flex-col items-center">
                    {!loading && <Image unoptimized src={avatar!} alt="User Avatar" width={100} height={100} className="rounded-[50%] mb-2" />}
                    <h3 className="text-2xl font-semibold">{user?.username || 'Guest'}</h3>
                </div>
            </div>
            <div className="flex flex-col w-full gap-2 p-4">
                <div className="flex flex-col">
                    <h2 className="font-medium tracking-wider mb-2 text-muted-foreground">General</h2>
                    <div className="flex flex-col gap-2">
                        <Link href="/" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                            activePage === '/' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                        )}>
                            <House className="w-5 h-5" />
                            <span>Home</span>
                        </Link>
                        <Link href="/games" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                            activePage === '/games' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                        )}>
                            <GamepadIcon className="w-5 h-5" />
                            <span>Games</span>
                        </Link>
                        <Link href="/games/favourites" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                            activePage === '/games/favourites' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                        )}>
                            <Heart className="w-5 h-5" />
                            <span>Favourites</span>
                        </Link>
                        <Link href="/games/recent" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                            activePage === '/games/recent' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                        )}>
                            <Clock className="w-5 h-5" />
                            <span>Recent</span>
                        </Link>
                    </div>
                </div>
                <div className="flex flex-col mt-4">
                    <h2 className="font-medium tracking-wider mb-2 text-muted-foreground">Account</h2>
                    <div className="flex flex-col gap-2">
                        {user ? (
                            <>
                                <Link href="/friends" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                                    activePage === '/friends' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                                )}>
                                    <div className="relative">
                                        <Users className="w-5 h-5" />
                                        <span className="absolute -top-1 -right-1 text-xs text-white bg-destructive rounded-full p-1"></span>
                                    </div>
                                    <span>Friends</span>
                                </Link>
                                <Link href="/messages" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                                    activePage === '/messages' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                                )}>
                                    <div className="relative">
                                        <MessageCircle className="w-5 h-5" />
                                        <span className="absolute -top-1 -right-1 text-xs text-white bg-destructive rounded-full p-1"></span>
                                    </div>
                                    <span>Messages</span>
                                </Link>
                                <Link href="/clips" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                                    activePage === '/clips' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                                )}>
                                    <Video className="w-5 h-5" />
                                    <span>Clips</span>
                                </Link>
                                <Link href="/crosshair" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                                    activePage === '/crosshair' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                                )}>
                                    <Crosshair className="w-5 h-5" />
                                    <span>Crosshair</span>
                                </Link>
                            </>
                        ) : (
                            <div onClick={() => signIn(null)} className="flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50">
                                <LogIn className="w-5 h-5" />
                                <span>Login</span>
                            </div>
                        )}
                        <Link href="/settings" className={cn("flex items-center rounded py-2 px-4 transition-colors duration-200 gap-2 text-white/50",
                            activePage === '/settings' ? "bg-primary text-primary-foreground" : "hover:bg-black/10 hover:text-white"
                        )}>
                            <Settings className="w-5 h-5" />
                            <span>Settings</span>
                        </Link>
                    </div>
                </div>
            </div>
        </aside>
    );
}

// src/components/Sidebar.vue
<script setup lang="ts">
defineProps({
    page: String
})

const auth = await useAuth();

const pfpUrl = /*auth.user ? (auth.user.photoURL || '../assets/img/default-photo.png') :*/ '../assets/img/default-photo.png';
const user = ref(auth.user);
const pfp = ref((await import(pfpUrl)).default);
</script>

<template>
    <aside id="sidebar">
        <div class="header">
            <div class="user" v-if="user != null">
                <img :src="pfp" alt="User photo" />
                <h3>{{ user.displayName }}</h3>
            </div>
            <div class="user" v-else>
                <img src="../assets/img/default-photo.png" alt="User photo" />
                <h3>Guest</h3>
            </div>
        </div>
        <div class="sections">
            <div class="section">
                <h2>General</h2>
                <div class="items">
                    <NuxtLink to="/" :class="{ item: true, active: page === 'home' }">
                        <Icon name="f7:house-fill" />
                        <span>Home</span>
                    </NuxtLink>
                    <NuxtLink to="/games" :class="{ item: true, active: page === 'games' }">
                        <Icon name="f7:gamecontroller-fill" />
                        <span>Games</span>
                    </NuxtLink>
                    <NuxtLink to="/favourites" :class="{ item: true, active: page === 'favourites' }">
                        <Icon name="mdi:heart" />
                        <span>Favourites</span>
                    </NuxtLink>
                    <NuxtLink to="/recentlyLaunched" :class="{ item: true, active: page === 'recentlyLaunched' }">
                        <Icon name="mdi:clock" />
                        <span>Recently Launched</span>
                    </NuxtLink>
                </div>
            </div>
            <div class="section">
                <h2>Account</h2>
                <div class="items" v-if="user != null">
                    <NuxtLink to="/friends" :class="{ item: true, active: page === 'friends' }">
                        <div class="icon">
                            <Icon name="mdi:account-group" />
                            <div class="alert"></div>
                        </div>
                        <span>Friends</span>
                        
                    </NuxtLink>
                    <NuxtLink to="/messages" :class="{ item: true, active: page === 'messages' }">
                        <div class="icon">
                            <Icon name="mdi:message" />
                            <div class="alert"></div>
                        </div>
                        <span>Messages</span>
                    </NuxtLink>
                    <NuxtLink to="/settings" :class="{ item: true, active: page === 'settings' }">
                        <Icon name="mdi:settings" />
                        <span>Settings</span>
                    </NuxtLink>
                </div>
                <div class="items" v-else>
                    <NuxtLink to="/login" :class="{ item: true, active: page === 'login' }">
                        <Icon name="mdi:login" />
                        <span>Login</span>
                    </NuxtLink>
                    <NuxtLink to="/register" :class="{ item: true, active: page === 'register' }">
                        <Icon name="mdi:register" />
                        <span>Register</span>
                    </NuxtLink>
                </div>
            </div>
        </div>
    </aside>
</template>

<style lang="scss">
#sidebar {
    width: 250px;
    height: 100%;
    background-color: var(--color-sidebar);
    color: var(--color-text);
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px 0;
    z-index: 900;
    transition: transform 0.3s;
    box-shadow: 2px 0 5px rgba(0, 0, 0, 0.2);

    .header {
        width: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 20px;

        .user {
            display: flex;
            flex-direction: column;
            align-items: center;

            img {
                width: 100px;
                height: 100px;
                border-radius: 50%;
                margin-bottom: 10px;
            }

            h3 {
                font-size: 1.5rem;
                font-weight: 700;
            }
        }
    }

    .sections {
        width: 100%;
        display: flex;
        flex-direction: column;
        padding: 1em;

        .section {
            width: 100%;
            display: flex;
            flex-direction: column;
            margin-bottom: 20px;

            h2 {
                font-size: 1rem;
                font-weight: 500;
                letter-spacing: 2px;
                text-transform: uppercase;
                margin-bottom: 10px;
            }

            .items {
                display: flex;
                flex-direction: column;
                gap: 4px;

                .item {
                    display: flex;
                    align-items: center;
                    padding: .5em 20px;
                    border-radius: 5px;
                    transition: background-color 0.3s;
                    color: rgba(255, 255, 255, 0.7);
                    gap: 10px;

                    &:hover {
                        background-color: rgba(255, 255, 255, 0.1);
                        color: var(--color-text);
                    }

                    &.active {
                        background-color: var(--color-primary);
                        color: var(--color-text);
                        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
                    }

                    .icon {
                        position: relative;

                        .alert {
                            position: absolute;
                            top: -2px;
                            right: -2px;
                            padding: 4px;
                            border-radius: 50%;
                            background-color: red;
                        }
                    }
                }
            }
        }
    }
}
</style>
